# 1 "data/maps/Route10_South_Frlg/scripts.pory"

# 2 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_South_Frlg_MapScripts::
# 3 "data/maps/Route10_South_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route10_South_Frlg/scripts.pory"

# 5 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_EventScript_SouthRockTunnelSign::
# 6 "data/maps/Route10_South_Frlg/scripts.pory"
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
# 7 "data/maps/Route10_South_Frlg/scripts.pory"
	end
# 8 "data/maps/Route10_South_Frlg/scripts.pory"

# 9 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_ClarkIntro::
# 10 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Ha-hahah-ah-ha!$"
# 11 "data/maps/Route10_South_Frlg/scripts.pory"

# 12 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_ClarkDefeat::
# 13 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Ha-haha!\n"
# 14 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Not laughing!\l"
# 15 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Ha-hay fever! Haha-ha-choo!$"
# 16 "data/maps/Route10_South_Frlg/scripts.pory"

# 17 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_ClarkPostBattle::
# 18 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Haha-ha-choo!\n"
# 19 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Ha-choo!\l"
# 20 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Snort! Snivel!$"
# 21 "data/maps/Route10_South_Frlg/scripts.pory"

# 22 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_HermanIntro::
# 23 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Hi, kid!\n"
# 24 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Want to see my POKéMON?$"
# 25 "data/maps/Route10_South_Frlg/scripts.pory"

# 26 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_HermanDefeat::
# 27 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Oh, no!\n"
# 28 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "My POKéMON!$"
# 29 "data/maps/Route10_South_Frlg/scripts.pory"

# 30 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_HermanPostBattle::
# 31 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I don't like you.\n"
# 32 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I don't like anyone better than me!$"
# 33 "data/maps/Route10_South_Frlg/scripts.pory"

# 34 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_TrentIntro::
# 35 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "Ah!\n"
# 36 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "This mountain air is delicious!$"
# 37 "data/maps/Route10_South_Frlg/scripts.pory"

# 38 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_TrentDefeat::
# 39 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "That cleared my head!$"
# 40 "data/maps/Route10_South_Frlg/scripts.pory"

# 41 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_TrentPostBattle::
# 42 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I feel bloated on mountain air!$"
# 43 "data/maps/Route10_South_Frlg/scripts.pory"

# 44 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_CarolIntro::
# 45 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I'm feeling a bit faint.\n"
# 46 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I haven't hiked in some time.$"
# 47 "data/maps/Route10_South_Frlg/scripts.pory"

# 48 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_CarolDefeat::
# 49 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I'm too tired.\n"
# 50 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I wasn't up for it.$"
# 51 "data/maps/Route10_South_Frlg/scripts.pory"

# 52 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_CarolPostBattle::
# 53 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "The POKéMON here in the mountains\n"
# 54 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "are so chunky…\p"
# 55 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "I wish there were pink POKéMON\n"
# 56 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "with a floral pattern!$"
# 57 "data/maps/Route10_South_Frlg/scripts.pory"

# 58 "data/maps/Route10_South_Frlg/scripts.pory"

# 59 "data/maps/Route10_South_Frlg/scripts.pory"
Route10_Text_RockTunnel::
# 60 "data/maps/Route10_South_Frlg/scripts.pory"
	.string "ROCK TUNNEL$"
