# 1 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 2 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_South_Frlg_MapScripts::
# 3 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 5 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_EventScript_RouteSign::
# 6 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	end
# 8 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 9 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_AbigailIntro::
# 10 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "I'm beginning to get a sunburn…$"
# 11 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 12 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_AbigailDefeat::
# 13 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "Oh, you're so awful.$"
# 14 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 15 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_AbigailPostBattle::
# 16 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "I like that cap you have.\n"
# 17 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "Maybe I should wear one, too…$"
# 18 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 19 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_GarrettIntro::
# 20 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "I took a break from swimming,\n"
# 21 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "only to have you challenge me?$"
# 22 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 23 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_GarrettDefeat::
# 24 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "Hey, what the…\n"
# 25 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "You're good, you!$"
# 26 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 27 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_GarrettPostBattle::
# 28 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "Instead of using SURF all the time,\n"
# 29 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "you should swim some.$"
# 30 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	
# 31 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_TanyaIntro::
# 32 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "There isn't a day in which we don't\n"
# 33 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "train!$"
# 34 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 35 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_TanyaDefeat::
# 36 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "I'm such a fool!$"
# 37 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 38 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_TanyaPostBattle::
# 39 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "I'll train even harder from now on!$"
# 40 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 41 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_BryceIntro::
# 42 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "You know, everything tastes great\n"
# 43 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "when you're out in the wild.$"
# 44 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 45 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_BryceDefeat::
# 46 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "Awww, blown!$"
# 47 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 48 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_BrycePostBattle::
# 49 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "The water in volcanic regions is\n"
# 50 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "delicious.$"
# 51 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 52 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_ClaireIntro::
# 53 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "My lunch filled us up, so will you\n"
# 54 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "battle us for some exercise?$"
# 55 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 56 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_ClaireDefeat::
# 57 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "That made me all sweaty.$"
# 58 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 59 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_ClairePostBattle::
# 60 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "What should I do?\n"
# 61 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "I feel famished again.$"
# 62 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"

# 63 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_RouteSign::
# 64 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "This is KINDLE ROAD.\p"
# 65 "data/maps/OneIsland_KindleRoad_South_Frlg/scripts.pory"
	.string "Go straight for MT. EMBER.$"
