# 1 "data/maps/Route4_West_Frlg/scripts.pory"

# 2 "data/maps/Route4_West_Frlg/scripts.pory"
Route4_West_Frlg_MapScripts::
# 3 "data/maps/Route4_West_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route4_West_Frlg/scripts.pory"

# 5 "data/maps/Route4_West_Frlg/scripts.pory"
Route4_EventScript_Unused::
# 6 "data/maps/Route4_West_Frlg/scripts.pory"
	end
# 7 "data/maps/Route4_West_Frlg/scripts.pory"

# 8 "data/maps/Route4_West_Frlg/scripts.pory"
Route4_EventScript_Woman::
# 9 "data/maps/Route4_West_Frlg/scripts.pory"
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
# 10 "data/maps/Route4_West_Frlg/scripts.pory"
	end
# 11 "data/maps/Route4_West_Frlg/scripts.pory"

# 12 "data/maps/Route4_West_Frlg/scripts.pory"
Route4_EventScript_MtMoonSign::
# 13 "data/maps/Route4_West_Frlg/scripts.pory"
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
# 14 "data/maps/Route4_West_Frlg/scripts.pory"
	end
# 15 "data/maps/Route4_West_Frlg/scripts.pory"
    
# 16 "data/maps/Route4_West_Frlg/scripts.pory"
Route4_Text_TrippedOverGeodude::
# 17 "data/maps/Route4_West_Frlg/scripts.pory"
	.string "Ouch! I tripped over a rocky\n"
# 18 "data/maps/Route4_West_Frlg/scripts.pory"
	.string "POKéMON, GEODUDE!$"
# 19 "data/maps/Route4_West_Frlg/scripts.pory"

# 20 "data/maps/Route4_West_Frlg/scripts.pory"
Route4_Text_MtMoonEntrance::
# 21 "data/maps/Route4_West_Frlg/scripts.pory"
	.string "MT. MOON\n"
# 22 "data/maps/Route4_West_Frlg/scripts.pory"
	.string "Tunnel Entrance$"
