# 1 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 2 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Mid_Frlg_MapScripts::
# 3 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 5 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_EventScript_EmberSpaSign::
# 6 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
# 7 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	end
# 8 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 9 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_FinnIntro::
# 10 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Seen from here, MT. EMBER towers\n"
# 11 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "into the sky.$"
# 12 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 13 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_FinnDefeat::
# 14 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Well, aren't you tough?$"
# 15 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 16 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_FinnPostBattle::
# 17 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "The sky is immense around these\n"
# 18 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "parts.$"
# 19 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 20 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_SharonIntro::
# 21 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Could you help me out with my\n"
# 22 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "training?$"
# 23 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 24 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_SharonDefeat::
# 25 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "You were a cut above me.$"
# 26 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 27 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_SharonPostBattle::
# 28 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "It's clear that you're skilled.\n"
# 29 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "I like you!$"
# 30 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 31 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_SheaIntro::
# 32 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Every morning, before breakfast,\n"
# 33 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "I swim around this island.$"
# 34 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 35 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_SheaDefeat::
# 36 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Gasp…\n"
# 37 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Gasp…$"
# 38 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 39 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_SheaPostBattle::
# 40 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "I lost because I'm pooped from all\n"
# 41 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "the running I did…$"
# 42 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 43 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_HughIntro::
# 44 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Dress appropriately for battle!\n"
# 45 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Lose that frivolous outfit!$"
# 46 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 47 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_HughDefeat::
# 48 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Why me?!$"
# 49 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 50 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_HughPostBattle::
# 51 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Even martial artists are becoming\n"
# 52 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "fashion conscious these days…$"
# 53 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 54 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_KiaIntro::
# 55 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "KIA: My big brother and I make\n"
# 56 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "an awesome combination!$"
# 57 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 58 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_KiaDefeat::
# 59 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "KIA: Huh?!\n"
# 60 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "I can't believe it!$"
# 61 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 62 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_KiaPostBattle::
# 63 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "KIA: How could there be anyone\n"
# 64 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "better than my big brother?$"
# 65 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 66 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_KiaNotEnoughMons::
# 67 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "KIA: If you want to battle with\n"
# 68 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "us, you have to bring at least two\l"
# 69 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "POKéMON with you.$"
# 70 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 71 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_MikIntro::
# 72 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "MIK: Together with KIA, I'm afraid\n"
# 73 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "of nothing!$"
# 74 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 75 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_MikDefeat::
# 76 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "MIK: Whoa!\n"
# 77 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "That's too much!$"
# 78 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 79 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_MikPostBattle::
# 80 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "MIK: How could my combination\n"
# 81 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "with KIA fail?$"
# 82 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 83 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_MikNotEnoughMons::
# 84 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "MIK: Hey, do you want to battle\n"
# 85 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "with us two?\p"
# 86 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Bring two or more POKéMON with\n"
# 87 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "you, then.$"
# 88 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"

# 89 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_EmberSpaSign::
# 90 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "Light the Fire in Your Heart!\n"
# 91 "data/maps/OneIsland_KindleRoad_Mid_Frlg/scripts.pory"
	.string "EMBER SPA$"
