# 1 "data/maps/Route10_North_Frlg/scripts.pory"

# 2 "data/maps/Route10_North_Frlg/scripts.pory"
Route10_North_Frlg_MapScripts::
# 3 "data/maps/Route10_North_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route10_North_Frlg/scripts.pory"

# 5 "data/maps/Route10_North_Frlg/scripts.pory"
Route10_EventScript_Unused::
# 6 "data/maps/Route10_North_Frlg/scripts.pory"
	end
# 7 "data/maps/Route10_North_Frlg/scripts.pory"

# 8 "data/maps/Route10_North_Frlg/scripts.pory"
Route10_EventScript_NorthRockTunnelSign::
# 9 "data/maps/Route10_North_Frlg/scripts.pory"
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
# 10 "data/maps/Route10_North_Frlg/scripts.pory"
	end
# 11 "data/maps/Route10_North_Frlg/scripts.pory"

# 12 "data/maps/Route10_North_Frlg/scripts.pory"
Route10_Text_HeidiIntro::
# 13 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "I've been out at a POKéMON GYM\n"
# 14 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "a few times.\p"
# 15 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "…But I always lose.$"
# 16 "data/maps/Route10_North_Frlg/scripts.pory"

# 17 "data/maps/Route10_North_Frlg/scripts.pory"
Route10_Text_HeidiDefeat::
# 18 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "Ohh!\n"
# 19 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "After all my training!$"
# 20 "data/maps/Route10_North_Frlg/scripts.pory"

# 21 "data/maps/Route10_North_Frlg/scripts.pory"
Route10_Text_HeidiPostBattle::
# 22 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "I noticed some POKéMANIACS\n"
# 23 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "prowling around.\p"
# 24 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "Can you imagine? Them?\n"
# 25 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "Up here in the mountains?$"
# 26 "data/maps/Route10_North_Frlg/scripts.pory"

# 27 "data/maps/Route10_North_Frlg/scripts.pory"
Route10_Text_RockTunnelDetourToLavender::
# 28 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "ROCK TUNNEL\n"
# 29 "data/maps/Route10_North_Frlg/scripts.pory"
	.string "Detour to LAVENDER TOWN$"
