# 1 "data/maps/Route2_South_Frlg/scripts.pory"

# 2 "data/maps/Route2_South_Frlg/scripts.pory"
Route2_South_Frlg_MapScripts::
# 3 "data/maps/Route2_South_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route2_South_Frlg/scripts.pory"

# 5 "data/maps/Route2_South_Frlg/scripts.pory"
Route2_EventScript_RouteSign::
# 6 "data/maps/Route2_South_Frlg/scripts.pory"
	msgbox Route2_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/Route2_South_Frlg/scripts.pory"
	end
# 8 "data/maps/Route2_South_Frlg/scripts.pory"

# 9 "data/maps/Route2_South_Frlg/scripts.pory"
Route2_Text_RouteSign::
# 10 "data/maps/Route2_South_Frlg/scripts.pory"
	.string "ROUTE 2\n"
# 11 "data/maps/Route2_South_Frlg/scripts.pory"
	.string "VIRIDIAN CITY - PEWTER CITY$"
