# 1 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"

# 2 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
OneIsland_KindleRoad_North_Frlg_MapScripts::
# 3 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"

# 5 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_MariaIntro::
# 6 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "The weather's gorgeous!\n"
# 7 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "Perfect for a battle!$"
# 8 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"

# 9 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_MariaDefeat::
# 10 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "Aiyeeeeh!$"
# 11 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"

# 12 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_MariaPostBattle::
# 13 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "Please don't splash my face!\n"
# 14 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "You'll ruin the makeup.$"
# 15 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"

# 16 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_TommyIntro::
# 17 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "Wait! Wait a second!\n"
# 18 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "I think I've hooked a big one!$"
# 19 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"

# 20 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_TommyDefeat::
# 21 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "I've lost it all again…$"
# 22 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"

# 23 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
OneIsland_KindleRoad_Text_TommyPostBattle::
# 24 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "Not only did I lose, the big one\n"
# 25 "data/maps/OneIsland_KindleRoad_North_Frlg/scripts.pory"
	.string "got away from me, too!$"
