Route2_ViridianCavern_SouthEntrance_Frlg_MapScripts::
	.byte 0


Route2_ViridianCavern_SouthEntrance_CaveIsMaze::
# 6 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	lock
# 7 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	faceplayer
# 8 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	msgbox Route2_ViridianCavern_SouthEntrance_CaveIsMaze_Text_0
# 9 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	release
	end


Route2_ViridianCavern_SouthEntrance_WickedBite::
# 15 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	lock
# 16 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	faceplayer
# 17 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	msgbox Route2_ViridianCavern_SouthEntrance_WickedBite_Text_0
# 18 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	release
	end


Route2_ViridianCavern_SouthEntrance_CaveIsMaze_Text_0:
# 8 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	.string "Are you going to VIRIDIAN CAVERN?\nIt's a natural maze in there. Be careful you don't get lost.$"

Route2_ViridianCavern_SouthEntrance_WickedBite_Text_0:
# 17 "data/maps/Route2_ViridianCavern_SouthEntrance_Frlg/scripts.pory"
	.string "ZUBAT may be small, but don't underestimate its wicked bite. Have you caught one already?$"
