# 1 "data/maps/Route11_West_Frlg/scripts.pory"

# 2 "data/maps/Route11_West_Frlg/scripts.pory"
Route11_West_Frlg_MapScripts::
# 3 "data/maps/Route11_West_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route11_West_Frlg/scripts.pory"

# 5 "data/maps/Route11_West_Frlg/scripts.pory"
Route11_EventScript_DiglettsCaveSign::
# 6 "data/maps/Route11_West_Frlg/scripts.pory"
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
# 7 "data/maps/Route11_West_Frlg/scripts.pory"
	end
# 8 "data/maps/Route11_West_Frlg/scripts.pory"

# 9 "data/maps/Route11_West_Frlg/scripts.pory"
Route11_Text_DiglettsCave::
# 10 "data/maps/Route11_West_Frlg/scripts.pory"
	.string "DIGLETT'S CAVE$"
