# 1 "data/maps/Route10_Mid_Frlg/scripts.pory"

# 2 "data/maps/Route10_Mid_Frlg/scripts.pory"
Route10_Mid_Frlg_MapScripts::
# 3 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route10_Mid_Frlg/scripts.pory"

# 5 "data/maps/Route10_Mid_Frlg/scripts.pory"
Route10_Mid_EventScript_Unused::
# 6 "data/maps/Route10_Mid_Frlg/scripts.pory"
	end
# 7 "data/maps/Route10_Mid_Frlg/scripts.pory"

# 8 "data/maps/Route10_Mid_Frlg/scripts.pory"
Route10_EventScript_PowerPlantSign::
# 9 "data/maps/Route10_Mid_Frlg/scripts.pory"
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
# 10 "data/maps/Route10_Mid_Frlg/scripts.pory"
	end
# 11 "data/maps/Route10_Mid_Frlg/scripts.pory"

# 12 "data/maps/Route10_Mid_Frlg/scripts.pory"
Route10_Text_MarkIntro::
# 13 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.string "Wow, you came all the way here?\n"
# 14 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.string "Maybe you're a POKéMANIAC, too?\l"
# 15 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.string "Want to see my collection?$"
# 16 "data/maps/Route10_Mid_Frlg/scripts.pory"

# 17 "data/maps/Route10_Mid_Frlg/scripts.pory"
Route10_Text_MarkDefeat::
# 18 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.string "Humph.\n"
# 19 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.string "I'm not angry!$"
# 20 "data/maps/Route10_Mid_Frlg/scripts.pory"

# 21 "data/maps/Route10_Mid_Frlg/scripts.pory"
Route10_Text_MarkPostBattle::
# 22 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.string "I have more rare POKéMON at home!$"
# 23 "data/maps/Route10_Mid_Frlg/scripts.pory"

# 24 "data/maps/Route10_Mid_Frlg/scripts.pory"
Route10_Text_PowerPlant::
# 25 "data/maps/Route10_Mid_Frlg/scripts.pory"
	.string "POWER PLANT$"
