# 1 "data/maps/Route4_East_Frlg/scripts.pory"

# 2 "data/maps/Route4_East_Frlg/scripts.pory"
Route4_East_Frlg_MapScripts::
# 3 "data/maps/Route4_East_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route4_East_Frlg/scripts.pory"

# 5 "data/maps/Route4_East_Frlg/scripts.pory"
Route4_EventScript_RouteSign::
# 6 "data/maps/Route4_East_Frlg/scripts.pory"
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/Route4_East_Frlg/scripts.pory"
	end
# 8 "data/maps/Route4_East_Frlg/scripts.pory"

# 9 "data/maps/Route4_East_Frlg/scripts.pory"
Route4_Text_CrissyIntro::
# 10 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "I came to MT. MOON in search of\n"
# 11 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "mushroom POKéMON.$"
# 12 "data/maps/Route4_East_Frlg/scripts.pory"

# 13 "data/maps/Route4_East_Frlg/scripts.pory"
Route4_Text_CrissyDefeat::
# 14 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "After all I did to catch them!$"
# 15 "data/maps/Route4_East_Frlg/scripts.pory"

# 16 "data/maps/Route4_East_Frlg/scripts.pory"
Route4_Text_CrissyPostBattle::
# 17 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "There might not be any more\n"
# 18 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "mushrooms here.\p"
# 19 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "I think I got them all.$"
# 20 "data/maps/Route4_East_Frlg/scripts.pory"

# 21 "data/maps/Route4_East_Frlg/scripts.pory"
Route4_Text_RouteSign::
# 22 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "ROUTE 4\n"
# 23 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "MT. MOON - CERULEAN CITY$"
# 24 "data/maps/Route4_East_Frlg/scripts.pory"

# 25 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaPunchTeach::
# 26 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "A punch of roaring ferocity!\p"
# 27 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Packed with destructive power!\p"
# 28 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "When the chips are down,\n"
# 29 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "MEGA PUNCH is the ultimate attack!\l"
# 30 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "You agree, yes?\p"
# 31 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Now!\n"
# 32 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Let me teach it to your POKéMON!$"
# 33 "data/maps/Route4_East_Frlg/scripts.pory"

# 34 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaPunchDeclined::
# 35 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "You'll be back when you understand\n"
# 36 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "the worth of MEGA PUNCH.$"
# 37 "data/maps/Route4_East_Frlg/scripts.pory"

# 38 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaPunchWhichMon::
# 39 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Fine!\n"
# 40 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Which POKéMON will learn it?$"
# 41 "data/maps/Route4_East_Frlg/scripts.pory"

# 42 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaPunchTaught::
# 43 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Now, we are comrades in the way of\n"
# 44 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "punching!\p"
# 45 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "You should go before you're seen\n"
# 46 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "by the misguided fool who trains\l"
# 47 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "only his silly kicking over there.$"
# 48 "data/maps/Route4_East_Frlg/scripts.pory"

# 49 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaKickTeach::
# 50 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "A kick of brutal ferocity!\p"
# 51 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Packed with destructive power!\p"
# 52 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "When you get right down to it,\n"
# 53 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "MEGA KICK is the ultimate attack!\l"
# 54 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Don't you agree?\p"
# 55 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Okay!\n"
# 56 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "I'll teach it to your POKéMON!$"
# 57 "data/maps/Route4_East_Frlg/scripts.pory"

# 58 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaKickDeclined::
# 59 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "You'll come crawling back when you\n"
# 60 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "realize the value of MEGA KICK.$"
# 61 "data/maps/Route4_East_Frlg/scripts.pory"

# 62 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaKickWhichMon::
# 63 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "All right!\n"
# 64 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Which POKéMON wants to learn it?$"
# 65 "data/maps/Route4_East_Frlg/scripts.pory"

# 66 "data/maps/Route4_East_Frlg/scripts.pory"
Text_MegaKickTaught::
# 67 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Now, we are soul mates in the way\n"
# 68 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "of kicking!\p"
# 69 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "You should run before you're seen\n"
# 70 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "by the deluded nitwit who trains\l"
# 71 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "only simple punching over there.$"
# 72 "data/maps/Route4_East_Frlg/scripts.pory"

# 73 "data/maps/Route4_East_Frlg/scripts.pory"
Route4_Text_PeopleLikeAndRespectBrock::
# 74 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "Oh, wow, that's the BOULDERBADGE!\n"
# 75 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "You got it from BROCK, didn't you?\p"
# 76 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "BROCK is cool. He's not just tough.\n"
# 77 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "People like and respect him.\p"
# 78 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "I want to become a GYM LEADER\n"
# 79 "data/maps/Route4_East_Frlg/scripts.pory"
	.string "like him.$"
